#!/bin/sh

sxhkd &
bash $HOME/.config/polybar/launch.sh  &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --set-scaled $HOME/.config/bg.jpg &

bspc monitor -d I II III IV V

bspc config border_width 2
bspc config window_gap 5

# bspc config focused_border_color '#6D6B8B'
bspc config focused_border_color '#F38BA8'
bspc config normal_border_color '#74C7EC'

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true